2024-07-05 18:26:36,693 INFO    MainThread:16546 [wandb_setup.py:_flush():76] Current SDK version is 0.17.4
2024-07-05 18:26:36,693 INFO    MainThread:16546 [wandb_setup.py:_flush():76] Configure stats pid to 16546
2024-07-05 18:26:36,693 INFO    MainThread:16546 [wandb_setup.py:_flush():76] Loading settings from /home/gaston/.config/wandb/settings
2024-07-05 18:26:36,693 INFO    MainThread:16546 [wandb_setup.py:_flush():76] Loading settings from /media/gaston/gaston1/DEV/ACTIA/workstation/scripts/wandb/settings
2024-07-05 18:26:36,693 INFO    MainThread:16546 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***', 'root_dir': '/media/gaston/gaston1/DEV/ACTIA/workstation/logs/Teachers/Unet', 'silent': 'true'}
2024-07-05 18:26:36,693 INFO    MainThread:16546 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-05 18:26:36,693 INFO    MainThread:16546 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'workstation/scripts/train.py', 'program_abspath': '/media/gaston/gaston1/DEV/ACTIA/workstation/scripts/train.py', 'program': '/media/gaston/gaston1/DEV/ACTIA/workstation/scripts/train.py'}
2024-07-05 18:26:36,694 INFO    MainThread:16546 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-05 18:26:36,694 INFO    MainThread:16546 [wandb_init.py:_log_setup():529] Logging user logs to /media/gaston/gaston1/DEV/ACTIA/workstation/logs/Teachers/Unet/wandb/run-20240705_182636-f12ypvth/logs/debug.log
2024-07-05 18:26:36,694 INFO    MainThread:16546 [wandb_init.py:_log_setup():530] Logging internal logs to /media/gaston/gaston1/DEV/ACTIA/workstation/logs/Teachers/Unet/wandb/run-20240705_182636-f12ypvth/logs/debug-internal.log
2024-07-05 18:26:36,694 INFO    MainThread:16546 [wandb_init.py:init():569] calling init triggers
2024-07-05 18:26:36,695 INFO    MainThread:16546 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {}
2024-07-05 18:26:36,695 INFO    MainThread:16546 [wandb_init.py:init():619] starting backend
2024-07-05 18:26:36,695 INFO    MainThread:16546 [wandb_init.py:init():623] setting up manager
2024-07-05 18:26:36,702 INFO    MainThread:16546 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-07-05 18:26:36,704 INFO    MainThread:16546 [wandb_init.py:init():631] backend started and connected
2024-07-05 18:26:36,716 INFO    MainThread:16546 [wandb_init.py:init():720] updated telemetry
2024-07-05 18:26:36,753 INFO    MainThread:16546 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-07-05 18:26:37,654 INFO    MainThread:16546 [wandb_run.py:_on_init():2402] communicating current version
2024-07-05 18:26:37,910 INFO    MainThread:16546 [wandb_run.py:_on_init():2411] got version response 
2024-07-05 18:26:37,911 INFO    MainThread:16546 [wandb_init.py:init():804] starting run threads in backend
2024-07-05 18:26:38,428 INFO    MainThread:16546 [wandb_run.py:_console_start():2380] atexit reg
2024-07-05 18:26:38,429 INFO    MainThread:16546 [wandb_run.py:_redirect():2235] redirect: wrap_raw
2024-07-05 18:26:38,429 INFO    MainThread:16546 [wandb_run.py:_redirect():2300] Wrapping output streams.
2024-07-05 18:26:38,430 INFO    MainThread:16546 [wandb_run.py:_redirect():2325] Redirects installed.
2024-07-05 18:26:38,433 INFO    MainThread:16546 [wandb_init.py:init():847] run started, returning control to user process
2024-07-05 18:26:38,434 INFO    MainThread:16546 [wandb_run.py:_config_callback():1382] config_cb None None {'batch_size': 4, 'lr': 0.0003, 'epochs': 4, 'step_size': 10, 'gamma': 0.5}
2024-07-05 18:33:55,263 INFO    MainThread:16546 [wandb_run.py:_finish():2109] finishing run https-www-supcom-tn-/my_project/f12ypvth
2024-07-05 18:33:55,290 INFO    MainThread:16546 [wandb_run.py:_atexit_cleanup():2349] got exitcode: 0
2024-07-05 18:33:55,299 INFO    MainThread:16546 [wandb_run.py:_restore():2332] restore
2024-07-05 18:33:55,303 INFO    MainThread:16546 [wandb_run.py:_restore():2338] restore done
